const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Camera3D,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Model3D,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.Shape3D,
		C3.Plugins.Spritefont2,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Model3D.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Model3D.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Model3D.Exps.Count,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Model3D.Exps.Y,
		C3.Plugins.Model3D.Acts.SetTransform,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Model3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Model3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Model3D.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Model3D.Exps.Progress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Model3D.Acts.SubInstanceVar,
		C3.Plugins.Model3D.Acts.SetAnimation,
		C3.Plugins.Model3D.Exps.Animation,
		C3.Plugins.Model3D.Cnds.PickDistance,
		C3.Plugins.Model3D.Exps.X,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Model3D.Cnds.OnAnimationFinished,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Model3D.Acts.SetX,
		C3.Plugins.Model3D.Exps.RotationZ,
		C3.Plugins.Model3D.Exps.RotationX,
		C3.Plugins.Model3D.Exps.RotationY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Model3D.Exps.ScaleX,
		C3.Plugins.Model3D.Exps.ScaleY,
		C3.Plugins.Model3D.Exps.ScaleZ,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Model3D.Cnds.CompareY,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Model3D.Acts.Destroy,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Model3D.Acts.AddInstanceVar,
		C3.Plugins.Model3D.Acts.SetModel,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Cnds.OnEnded
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{AJAX: 0},
	{JSON: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Variables: 0},
	{"3DCamera": 0},
	{Anchor: 0},
	{til: 0},
	{startX: 0},
	{burguers: 0},
	{scale: 0},
	{hit: 0},
	{fight: 0},
	{Tween: 0},
	{Flash: 0},
	{player: 0},
	{playing: 0},
	{dragging: 0},
	{touchX: 0},
	{touchY: 0},
	{gamespeed: 0},
	{defeat: 0},
	{win: 0},
	{ScrollTo: 0},
	{gamemanager: 0},
	{Rotate: 0},
	{roller: 0},
	{one_rotator: 0},
	{single_rotator: 0},
	{available: 0},
	{energy: 0},
	{hamburger: 0},
	{number_3d: 0},
	{"3DShape": 0},
	{burguer_ui: 0},
	{name: 0},
	{txtUI: 0},
	{btnSound: 0},
	{burger: 0},
	{candestroy: 0},
	{wall: 0},
	{DrawingCanvas: 0},
	{txtUI3: 0},
	{txtUI2: 0},
	{number_ui: 0},
	{lettuce: 0},
	{dead: 0},
	{chef: 0},
	{boxing_ring: 0},
	{boss: 0},
	{transition: 0},
	{Sine: 0},
	{btn_cont: 0},
	{Bullet: 0},
	{confeti_particles: 0},
	{logo: 0},
	{FadeIn: 0},
	{FadeOut: 0},
	{hand: 0},
	{tutorial: 0},
	{txtUI1: 0},
	{tomato: 0},
	{double_rotator: 0},
	{two_rotator: 0},
	{player_masc: 0},
	{rotator_masc: 0},
	{goGame: 0},
	{Fade: 0},
	{taptoplay: 0},
	{Environment: 0},
	{Food: 0},
	{Buttons: 0},
	{Rotators: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{posXConfeti: 0},
	{posYConfeti: 0},
	{nLayer: 0},
	{lastSpawnY: 0},
	{nChunks: 0},
	{ChunksLoaded: 0},
	{categoria: 0},
	{chunkIndex: 0},
	{totalObjEnChunk: 0},
	{totalEnCategoria: 0},
	{objType: 0},
	{objX: 0},
	{objY: 0},
	{chunkCount: 0},
	{BASESPEED: 0},
	{shakeDuration: 0},
	{shakeIntensity: 0},
	{shakeTimer: 0},
	{Level: 0},
	{mag: 0},
	{dur: 0},
	{offsetX: 0},
	{offsetY: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Variables: class extends self.IArrayInstance {},
	_3DCamera: class extends self.IInstance {},
	til: class extends self.ITiledBackgroundInstance {},
	player: class extends self.I3DModelInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	roller: class extends self.I3DModelInstance {},
	one_rotator: class extends self.I3DModelInstance {},
	single_rotator: class extends self.ISpriteInstance {},
	hamburger: class extends self.I3DModelInstance {},
	number_3d: class extends self.I3DShapeInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	burguer_ui: class extends self.I3DModelInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	btnSound: class extends self.ISpriteInstance {},
	wall: class extends self.I3DModelInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	txtUI3: class extends self.ISpriteFontInstance {},
	txtUI2: class extends self.ISpriteFontInstance {},
	number_ui: class extends self.ISpriteInstance {},
	lettuce: class extends self.I3DModelInstance {},
	chef: class extends self.I3DModelInstance {},
	boxing_ring: class extends self.I3DModelInstance {},
	boss: class extends self.I3DModelInstance {},
	transition: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	btn_cont: class extends self.ISpriteInstance {},
	confeti_particles: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	txtUI1: class extends self.ISpriteFontInstance {},
	tomato: class extends self.I3DModelInstance {},
	double_rotator: class extends self.ISpriteInstance {},
	two_rotator: class extends self.I3DModelInstance {},
	player_masc: class extends self.ISpriteInstance {},
	rotator_masc: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	Environment: class extends self.I3DModelInstance {},
	Food: class extends self.I3DModelInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Rotators: class extends self.I3DModelInstance {}
}